# Generated by Django 5.1.3 on 2024-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_client_owner_log_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("started", "started"),
                    ("done", "done"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
