# Generated by Django 4.2.2 on 2024-11-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_change_status", "Can change status")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
